language: scala
scala: 2.11.8
env: 
- JDK=oraclejdk8
jdk:
- oraclejdk8

script:
 - sbt -jvm-opts travis/jvmopts.compile compile
 - sbt -jvm-opts travis/jvmopts.test test
 - sbt -jvm-opts travis/jvmopts.test scalastyle
 - sbt clean coverage test coverageReport
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.m2/repository

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - test $TRAVIS_BRANCH = "master" && ./trigger_core_repo_build.sh

before_script:
  - sudo chmod +x /usr/local/bin/sbt
